version: '3'
services:
  cliente-persona-service:
    image: cliente-persona-service:latest
    ports:
      - "8081:8081"
    networks:
      - microservice-network
    depends_on:
      - rabbitmq

  cuenta-movimientos-service:
    image: cuenta-movimientos-service:latest
    ports:
      - "8082:8082"
    networks:
      - microservice-network
    depends_on:
      - rabbitmq

  rabbitmq:
    image: rabbitmq:3-management
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - microservice-network

networks:
  microservice-network:
    driver: bridge
